name: Render y Publica Quarto en Main

on:
  push:
    branches:
      - main

jobs:
  render-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v3
        
      - name: Configurar R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.4.2'

      - name: Configurar Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Renderizar sitio con Quarto
        uses: quarto-dev/quarto-actions/render@v2
        with:
          path: .  # o la ruta donde se encuentran tus archivos QMD

      - name: Copiar archivo CNAME al directorio de salida
        run: cp CNAME _site/

      - name: Publicar en GitHub Pages sobre main
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: _site
          publish_branch: main
          keep_files: true
